Repository ElixirSeattle/xebow, pull requests merged in 2020-08, with the labels that each got.

#95 Move animation management out of Engine
  lib/rgb_matrix/animation.ex
  lib/rgb_matrix/animation/breathing.ex
  lib/rgb_matrix/animation/cycle_all.ex
  lib/rgb_matrix/animation/hue_wave.ex
  lib/rgb_matrix/animation/pinwheel.ex
  lib/rgb_matrix/animation/random_keypresses.ex
  lib/rgb_matrix/animation/random_solid.ex
  lib/rgb_matrix/animation/solid_color.ex
  lib/rgb_matrix/animation/solid_reactive.ex
  lib/rgb_matrix/engine.ex
  lib/xebow.ex
  lib/xebow/application.ex
  lib/xebow/keyboard.ex
  lib/xebow/leds.ex
  lib/xebow_web/live/matrix_live.ex
Labels: refactor

#100 Update the note about the project being in early development
  README.md
Labels: documentation

#101 Add link to wireframes in readme
  README.md
Labels: documentation

#98 New UI main page
  assets/css/app.scss
  assets/css/button.scss
  assets/css/fontawesome.scss
  assets/css/keypad.scss
  assets/css/lato.scss
  assets/css/live_view.scss
  assets/css/phoenix.css
  assets/css/select.scss
  assets/css/slider.scss
  assets/js/app.js
  assets/package-lock.json
  assets/package.json
  assets/postcss.config.js
  assets/tailwind.config.js
  assets/webpack.config.js
  lib/xebow_web/live/animation_config_integer_component.html.leex
  lib/xebow_web/live/animation_config_option_component.html.leex
  lib/xebow_web/live/matrix_live.ex
  lib/xebow_web/live/matrix_live.html.leex
  lib/xebow_web/templates/layout/_nav.html.eex
  lib/xebow_web/templates/layout/app.html.eex
  lib/xebow_web/templates/layout/live.html.leex
  lib/xebow_web/templates/layout/root.html.leex
Labels: feature

#97 Update nerves system to v2.0.0-rc.0+keybow.1
  config/keybow/config.exs
  lib/xebow/application.ex
  mix.exs
  mix.lock
Labels: refactor

#107 Only validate firmware on target
  lib/xebow/application.ex
Labels: bug

#106 Improve `use Animation` experience
  lib/rgb_matrix/animation.ex
  lib/rgb_matrix/animation/breathing.ex
  lib/rgb_matrix/animation/config.ex
  lib/rgb_matrix/animation/config/field_type.ex
  lib/rgb_matrix/animation/config/field_type/integer.ex
  lib/rgb_matrix/animation/config/field_type/option.ex
  lib/rgb_matrix/animation/cycle_all.ex
  lib/rgb_matrix/animation/hue_wave.ex
  lib/rgb_matrix/animation/pinwheel.ex
  lib/rgb_matrix/animation/random_keypresses.ex
  lib/rgb_matrix/animation/random_solid.ex
  lib/rgb_matrix/animation/solid_color.ex
  lib/rgb_matrix/animation/solid_reactive.ex
  test/rgb_matrix/animation/config_test.exs
Labels: refactor

#110 Refactor telemetry link to use 'Routes' helper
  lib/xebow_web/templates/layout/_nav.html.eex
  lib/xebow_web/templates/layout/root.html.leex
Labels: refactor

#114 Check current value of option fields
  lib/xebow_web/live/animation_config_option_component.html.leex
Labels: bug

#109 Create animations page
  .gitignore
  assets/css/app.scss
  assets/css/dropdown.scss
  assets/css/toggle.scss
  assets/js/app.js
  assets/js/dropdown.js
  config/host/dev.exs
  config/host/test.exs
  config/keybow/config.exs
  lib/rgb_matrix/animation.ex
  lib/xebow.ex
  lib/xebow/application.ex
  lib/xebow/settings.ex
  lib/xebow_web/live/animations_live.ex
  lib/xebow_web/live/animations_live.html.leex
  lib/xebow_web/live/matrix_live.ex
  lib/xebow_web/live/matrix_live.html.leex
  lib/xebow_web/router.ex
  lib/xebow_web/templates/layout/_nav.html.eex
  lib/xebow_web/templates/layout/root.html.leex
  mix.exs
  test/rgb_matrix/animation_test.exs
  test/support/conn_case.ex
  test/xebow/settings_test.exs
  test/xebow_test.exs
  test/xebow_web/live/animations_live_test.exs
Labels: dependencies

#115 Fix Xebow crash when cycling animations and none are active
  lib/xebow.ex
Labels: bug

#116 Improve `Config` field casting, errors, and documentation
  lib/rgb_matrix/animation/config.ex
  lib/rgb_matrix/animation/config/field_type.ex
  lib/rgb_matrix/animation/config/field_type/integer.ex
  lib/rgb_matrix/animation/config/field_type/option.ex
  test/rgb_matrix/animation/config/field_type/integer_test.exs
  test/rgb_matrix/animation/config/field_type/option_test.exs
  test/rgb_matrix/animation/config_test.exs
Labels: refactor

#119 Configure USB gadget device before the BEAM boots
  lib/xebow/application.ex
  lib/xebow/hid_gadget.ex
  lib/xebow/keyboard.ex
  mix.exs
  mix.lock
  rootfs_overlay/etc/erlinit.config
  rootfs_overlay/etc/pre-run.sh
  rootfs_overlay/etc/usb_gadget/hidg.schema
Labels: refactor

#120 Only advertise the web interface as a network service
  config/keybow/config.exs
Labels: refactor

#121 Define keys and LEDs in target config
  config/host/config.exs
  config/host/test.exs
  config/keybow/config.exs
  lib/layout.ex
  lib/xebow.ex
  test/layout/key_test.exs
  test/layout/led_test.exs
  test/layout_test.exs
Labels: refactor
