Repository ElixirSeattle/xebow, pull requests merged in 2020-07, with the labels that each got.

#41 Add community resources to readme
  README.md
Labels: documentation

#48 Set mix target to keybow when building firmware
  mix.exs
Labels: feature

#47 Add tests for engine
  lib/xebow/application.ex
  lib/xebow/engine.ex
  test/engine_test.exs
  test/test_helper.exs
  test/xebow_test.exs
Labels: refactor

#50 refactor animation cycling
  lib/xebow/engine.ex
  lib/xebow/keys.ex
Labels: refactor

#55 Add mix upload command
  README.md
  mix.exs
Labels: feature

#57 Refactor dialyzer path
  mix.exs
Labels: refactor

#60 Use mix upload command from the latest nerves_firmware_ssh
  mix.exs
  mix.lock
  upload.sh
Labels: refactor

#56 Add live-view with real-time animation view
  .formatter.exs
  .github/workflows/ci.yml
  .gitignore
  assets/.babelrc
  assets/css/app.scss
  assets/css/phoenix.css
  assets/js/app.js
  assets/package-lock.json
  assets/package.json
  assets/static/favicon.ico
  assets/static/images/phoenix.png
  assets/static/robots.txt
  assets/webpack.config.js
  config/config.exs
  lib/rgb_matrix/animation.ex
  lib/rgb_matrix/animation/config.ex
  lib/rgb_matrix/engine.ex
  lib/rgb_matrix/paintable.ex
  lib/xebow/application.ex
  lib/xebow/leds.ex
  lib/xebow_web.ex
  lib/xebow_web/channels/user_socket.ex
  lib/xebow_web/endpoint.ex
  lib/xebow_web/live/animation_config_component.ex
  lib/xebow_web/live/animation_config_component.html.leex
  lib/xebow_web/live/animation_config_integer_component.ex
  lib/xebow_web/live/animation_config_integer_component.html.leex
  lib/xebow_web/live/animation_config_option_component.ex
  lib/xebow_web/live/animation_config_option_component.html.leex
  lib/xebow_web/live/matrix_live.ex
  lib/xebow_web/live/matrix_live.html.leex
  lib/xebow_web/router.ex
  lib/xebow_web/telemetry.ex
  lib/xebow_web/templates/layout/app.html.eex
  lib/xebow_web/templates/layout/live.html.leex
  lib/xebow_web/templates/layout/root.html.leex
  lib/xebow_web/views/error_helpers.ex
  lib/xebow_web/views/error_view.ex
  lib/xebow_web/views/layout_view.ex
  mix.exs
  mix.lock
Labels: feature

#62 Enable Phoenix on localhost
  config/config.exs
  config/host/config.exs
  config/host/dev.exs
  config/host/test.exs
  config/keybow/config.exs
  config/keybow/dev.exs
  lib/xebow/application.ex
  mix.exs
Labels: feature

#75 Compile static assets when building the firmware bundle
  mix.exs
Labels: feature

#76 Add mix firmware.upload alias
  README.md
  mix.exs
Labels: feature

#79 Finishing touches for running on the host
  README.md
  config/config.exs
  config/keybow/config.exs
  lib/xebow/application.ex
  lib/xebow/hid_gadget.ex
  lib/xebow/keyboard.ex
  lib/xebow/leds.ex
  mix.exs
Labels: feature

#87 Change layout Key and LED float types to number
  lib/layout.ex
  lib/layout/key.ex
  lib/layout/led.ex
Labels: bug

#77 Architecture: Component flow
  design/architecture/component-flow.md
  design/architecture/component-flow.png
Labels: documentation

#85 Add credo to CI pipeline
  .credo.exs
  .github/workflows/ci.yml
  lib/rgb_matrix.ex
  lib/rgb_matrix/animation/breathing.ex
  lib/rgb_matrix/animation/config.ex
  lib/rgb_matrix/animation/hue_wave.ex
  lib/rgb_matrix/animation/solid_color.ex
  lib/rgb_matrix/animation/solid_reactive.ex
  lib/xebow.ex
  lib/xebow/hid_gadget.ex
  lib/xebow/keyboard.ex
  lib/xebow_web/live/animation_config_component.ex
  lib/xebow_web/live/animation_config_integer_component.ex
  lib/xebow_web/live/animation_config_option_component.ex
  lib/xebow_web/live/matrix_live.ex
  lib/xebow_web/telemetry.ex
  mix.exs
  mix.lock
Labels: feature

#88 Update dependencies
  assets/package-lock.json
  assets/package.json
  assets/webpack.config.js
  mix.exs
  mix.lock
Labels: refactor

#86 Decrease the data transferred for live view
  assets/js/app.js
  lib/xebow_web/live/animation_config_integer_component.html.leex
  lib/xebow_web/live/matrix_live.ex
  lib/xebow_web/live/matrix_live.html.leex
Labels: refactor

#93 Rework Mix tasks for asset compilation and installation
  mix.exs
Labels: bug

#94 Add NCM to networking configuration for OSX Catalina (10.15) compatibility
  lib/xebow/hid_gadget.ex
  mix.exs
  mix.lock
Labels: bug, dependencies
